# Generated by Django 4.2.3 on 2023-07-22 15:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='product_type',
        ),
        migrations.AddField(
            model_name='product',
            name='product_main_imge',
            field=models.ImageField(blank=True, null=True, upload_to='product main imge/', verbose_name='Main Image'),
        ),
    ]
